//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma
{
    using System;
    using System.Collections.Generic;
    
    public partial class GanttView
    {
        public string Название { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Крайний_срок { get; set; }
        public string Статус { get; set; }
    }
}
